#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const providersPath = resolve(root, "src/data/providers.json");
const readmePath = resolve(root, "README.md");

const providers = JSON.parse(readFileSync(providersPath, "utf8"));

const sorted = [...providers].sort((a, b) => {
  if (a.asymmetric !== b.asymmetric) return a.asymmetric ? -1 : 1;
  return a.name.localeCompare(b.name);
});

const total = providers.length;
const asymmetricCount = providers.filter((p) => p.asymmetric).length;
const pct = ((asymmetricCount / total) * 100).toFixed(0);

const escape = (s) => String(s).replace(/\|/g, "\\|");

const row = (p) =>
  `| ![](https://www.google.com/s2/favicons?sz=32&domain=${p.domain}) **${escape(p.name)}** | ${escape(p.category)} | ${p.asymmetric ? "Asymmetric" : "Shared secret"} | \`${escape(p.scheme)}\` | [docs](${p.docs}) |`;

const tableHeader = [
  "| Provider | Category | Verification | Scheme | Docs |",
  "| --- | --- | --- | --- | --- |",
].join("\n");

const md = `# Are we asymmetric yet?

SaaS webhook signing schemes, ranked by verifiability without a shared secret.

> **${asymmetricCount} / ${total}** providers (${pct}%) sign webhooks asymmetrically — meaning consumers can verify them with only a public key, no shared secret required.

## Legend

- **Asymmetric** — verifying webhooks requires no secret key material on the consumer.
- **Shared secret** — verifying requires key material on the consumer (HMAC or static token); anyone with it can forge webhooks.

## Providers

${tableHeader}
${sorted.map(row).join("\n")}

## Contributing

Spotted a missing or wrong entry? This list is open source — PRs and issues welcome at [movitz-s/are-we-asymmetric-yet](https://github.com/movitz-s/are-we-asymmetric-yet).

---

<sub>Generated from \`src/data/providers.json\` by \`scripts/generate-readme.mjs\`. Do not edit this file by hand.</sub>
`;

writeFileSync(readmePath, md);
console.log(`Wrote ${readmePath} (${total} providers, ${asymmetricCount} asymmetric)`);
